### ISSUE TITLE
Duplicating Questionnaire gives coding error detected message

### ISSUE THREAD

**Issue by rebelsoxuk** [remotelearner/moodle-mod_questionnaire#84] opened 2017-04-10 10:44 UTC
Hi.

Since the recent Questionnaire update, one of our admin staff have tried to duplicate a previous questionnaire and received this message:

**Coding error detected, it must be fixed by a programmer: encode_content_links() method needs to be overridden in each subclass of backup_activity_task**

Any ideas on what might be wrong? 

Moodle 3.2.2+ (Build: 20170407) Version 2016120502.05

![image005](https://cloud.githubusercontent.com/assets/6031722/24858152/f6f6880a-1de2-11e7-8a12-dddbcb94b22b.jpg)

Regards

bobby

**Comment by mchurchward** [comment] 2017-04-10 16:29
Can you please report what version of the questionnaire plugin you are using? The most current version for Moodle 3.2 is "﻿Release 3.2.3 (Build - 2017033000)". I tried that version and cannot replicate the problem you described.

**Comment by rebelsoxuk** [comment] 2017-04-10 20:09
3.2.3 (Build - 2017033000) is the version we're using.

If you go to the RH side of any topic there is an option to Edit Settings, under this is the option to Duplicate.
That's how she's trying to do it.

Regards

**Comment by mchurchward** [comment] 2017-04-10 20:31
I can't replicate that problem. When I use duplicate from the edit menu (course has editing on, edit menu for the activity), the duplicate action works fine.

Can you turn on the debugging for the site and capture any errors that are displayed? Need files and line numbers to see why it is not working on your site.

**Comment by rebelsoxuk** [comment] 2017-04-11 09:47
Stranger, as I've created a test questionnaire in a different Moodle installation (with same version) and had the exact same error message.... Here is the debug message from that site (debug set to Developer Mode)

* line 357 of /backup/moodle2/backup_activity_task.class.php: coding_exception thrown
* line 62 of /mod/tutorialbooking/backup/moodle2/backup_tutorialbooking_activity_task.class.php: call to backup_activity_task::encode_content_links()
* line ? of unknownfile: call to backup_tutorialbooking_activity_task::encode_content_links()
* line 125 of /backup/moodle2/backup_xml_transformer.class.php: call to call_user_func()
* line 88 of /backup/moodle2/backup_xml_transformer.class.php: call to backup_xml_transformer->encode_absolute_links()
* line 273 of /backup/util/xml/xml_writer.class.php: call to backup_xml_transformer->process()
* line 211 of /backup/util/xml/xml_writer.class.php: call to xml_writer->text_content()
* line 110 of /backup/util/structure/backup_structure_processor.class.php: call to xml_writer->full_tag()
* line 38 of /backup/util/structure/backup_final_element.class.php: call to backup_structure_processor->process_final_element()
* line 97 of /backup/util/structure/backup_nested_element.class.php: call to backup_final_element->process()
* line 107 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->process()

**Comment by mchurchward** [comment] 2017-04-11 14:36
It looks like the problem isn't with questionnaire. Your error message indicates it is a problem with a plugin called "tutorialbooking" (_line 62 of /mod/tutorialbooking/backup/moodle2/backup_tutorialbooking_activity_task.class.php: call to backup_activity_task::encode_content_links()_)

**Comment by mchurchward** [comment] 2017-04-13 20:14
Hi. Did you determine if the problem was in "tutorialbooking"? Can I close this issue?

**Closed** 2017-04-17 13:41 UTC

**Comment by rebelsoxuk** [comment] 2017-04-18 10:49
Hi.
Apologies, I've been away for the Easter break. I removed the Tutorialbooking plugin and it sorted out the problem.
Thanks for your assistance.
Regards
