### ISSUE TITLE
Fix for empty print popup in individual responses

### ISSUE THREAD

**Issue by mwehr** [remotelearner/moodle-mod_questionnaire#76] opened 2017-02-01 16:43 UTC
Hi,

Printing the results for an individual response gives a blank page.
The issues seems in the print.php line 44 where the used output page object is the wrong one.
Changing it to the reportpage object
```php
$questionnaire->add_page(new \mod_questionnaire\output\reportpage());
```
fixes the problem

Kind regards
Mario

**Comment by mchurchward** [comment] 2017-02-01 19:12
Hi. Thanks for the report. Can you tell me what version of the questionnaire is causing this? Also, how do I execute the steps to access the print function you are seeing the problem with?

**Comment by mwehr** [comment] 2017-02-01 19:27
Hi,

We are using the MOODLE_32_STABLE branch.

Steps to reproduce:
Assuming you have a questionnaire instance with responses.
Goto questionnaire instance
Select Tab -> View All Responses
Select Sub-Tab -> List of responses
Select a particpant to show his individual response
Select Print this Response
A PopUp with title and without individual response information is shown.

**Comment by mchurchward** [comment] 2017-02-01 19:38
Okay. Now I see.
It looks like the fix is a bit more complicated than the one you supplied though. Before your fix, the print blank questionnaire from the preview page works and the print response doesn't. After the fix, the print response works but the print blank doesn't.
So something in the print.php script needs to know the difference between the two print functions.

**Comment by mchurchward** [comment] 2017-02-01 19:43
I think this fix works for both. Change line 44 (as you noted) to the following lines:

if (!empty($rid)) {
    $questionnaire->add_page(new \mod_questionnaire\output\reportpage());
} else {
    $questionnaire->add_page(new \mod_questionnaire\output\previewpage());
}

**Comment by mchurchward** [comment] 2017-02-01 19:49
I have created https://tracker.moodle.org/browse/CONTRIB-6730 to track this issue.

**Comment by mwehr** [comment] 2017-02-01 20:10
Jup,.. great works like a charm :-)

One more thing I noticed.....
If switching Moodle to debug mode the execution of the print.php triggers a warning about using the $PAGE without a URL set.
This could be fixed if you move 
```php
$url = new moodle_url($CFG->wwwroot.'/mod/questionnaire/print.php');
$PAGE->set_url($url);
```
before 
```php
// Add renderer and page objects to the questionnaire object for display use.
$questionnaire->add_renderer($PAGE->get_renderer('mod_questionnaire'));
```

**Comment by mchurchward** [comment] 2017-02-03 19:59
I can't reproduce that.
I'm going to close this issue. If you think the warning is still being triggered with the latest release, please open a new issue.

**Closed by mchurchward** 2017-02-03 19:59 UTC
