### ISSUE TITLE
3.1beta: Adding question doesn't work

### ISSUE THREAD

**Issue by Jarvil** [remotelearner/moodle-mod_questionnaire#64] opened 2016-04-26 11:15 UTC
Hello,

I'm testing Questionnaire-plugin 3.1beta (Build - 2016020200) on Moodle 3.1dev 
build: 20160422)

When I'm adding any new question to my questionnaire and press "add question" it flashes an error for a few seconds then takes me to an white page. No questions are added and if I come back to the questionnare and click the course name in the breadcrumb it displays only a white page 

See attachement for error

(B
![questionnare_error](https://cloud.githubusercontent.com/assets/15193418/14816386/49123022-0bb9-11e6-8c4a-c51414e3b576.png)

**Comment by mchurchward** [comment] 2016-04-26 15:20
Hi. Thanks for the report.
Unfortunately I cannot replicate this problem. The error message you are posting is a developer warning, that does need to be dealt with, but is not causing any problems. It is just saying that it is something that will need to be dealt with.
Is this a new questionnaire or an existing one? Is is a specific type of question causing the error?
A blank page is usually caused by a missing "class". Can you verify that all files in the module directory are accessible?
Lastly, what database technology are you using?

**Comment by mchurchward** [comment] 2016-04-26 19:50
Actually, if you re running PHP 7, these issues might be related. I created MDL-52471 to fix this, and have pushed a fix to the master branch. If you check out the latest in master, the warning you reported should be gone. Can you see if it also fixes the blank page error?

**Comment by Jarvil** [comment] 2016-04-27 09:02
Hello,

We are using MySQL and PHP Version 5.6.19-0+deb8u1. I'm using teacher role, Internet Explorer 11 and clean theme. 

We just updated the latest version from the master branch and the problem continues.

1. Log in to the course as teacher
2. Create new questionnare
3. Give name
4. Change "Save/Resume answers", "Allow branching questions" to "yes"
5. Change "Submission grade" to "100"
6. Save
7. Start adding question (type doesn't matter) 
8. Type all required quesstion information and press "save changes"
9. You are now redirected to a white page
10. Select the URL and click ENTER
11. Page will now load an give error

Debug info: 
Error code: missingparam 

× Stack trace: •line 495 of /lib/setuplib.php: moodle_exception thrown
•line 552 of /lib/moodlelib.php: call to print_error()
•line 21 of /mod/questionnaire/questions.php: call to required_param()

12. Return to edit the Questionnare, you can see the question is added. So we still have "white page" error in the step 9.

**Comment by Jarvil** [comment] 2016-04-27 09:11
I have uploaded video here:

http://sendvid.com/pv3ta01l?secret=bf8a3421-98df-43ab-8750-0bf7097372e1

**Comment by mchurchward** [comment] 2016-04-27 17:14
Hi. I saw the "object" warnings in your video. It looks like I missed some occurrences of this. The latest in master (pushed just now) should have all of them fixed.

**Comment by Jarvil** [comment] 2016-04-28 11:16
Hello,

Now everything seems to work fine, no more white pages, thank you :+1:

**Closed** 2016-09-28 17:08 UTC
