### ISSUE TITLE
Behat command 'And I add a "Questionnaire" to section "1" and I fill the form with' is deprecated

### ISSUE THREAD

**Issue by lucaboesch** [remotelearner/moodle-mod_questionnaire#597] opened 2024-08-28 07:55 UTC
Instead of 'And I add a "Questionnaire" to section "1" and I fill the form with' it should be 'And I add a questionnaire activity to course "Course 1" section "1" and I fill the form with:'.

**Comment by leonstr** [comment] 2024-08-28 12:13
Duplicate of #585?

**Comment by lucaboesch** [comment] 2024-08-28 14:56
Yeah, right.
Closing.

**Closed as completed** 2024-08-28 14:56 UTC
